enum ErrorType {ERR_NONE, ERR_BOARDPASS, ERR_BOARDADVANCE, ERR_GENERAL};
enum Mode {MODE_IDLE, MODE_WORKING, MODE_ESTOPPED, MODE_ERROR, MODE_TESTLEDS, MODE_TESTPHOTOINTS, MODE_TESTBUTTONS, MODE_TESTBOARDPRESS, MODE_TESTCARRAIGE};
