enum ErrorType {ERR_NONE, ERR_UPPER_BOARD_PASS, ERR_LOWER_BOARD_PASS, ERR_CARRAIGE_ADVANCE, ERR_GENERAL, ERR_TESTBED_NOT_READY, ERR_TESTBED_SELFTEST, ERR_TESTBED_TIMEOUT};
enum Mode {MODE_IDLE, MODE_BEGIN_WORKING, MODE_WORKING, MODE_ESTOPPED, MODE_ERROR, MODE_TESTLEDS, MODE_TESTPHOTOINTS, MODE_TESTBUTTONS, MODE_TESTBOARDPRESS, MODE_TESTCARRAIGE, MODE_TESTGARBAGE};
enum bedStatus {BED_NOT_READY, BED_SELF_TEST, BED_READY, BED_TEST_BUSY};
enum testResultCode {TEST_PASS, TEST_FAIL, TEST_ABORT, TEST_TIMEOUT};
